Repository taikoxyz/simple-taiko-node, pull requests merged in 2024-09, with the labels that each got.

#329 feat(prover,proposer,driver): bump l2ee and driver versions for hekla
  docker-compose-hekla.yml
Labels: area.client, area.prover, area.proposer

#330 feat(prover,proposer,driver): bump client version
  docker-compose-hekla.yml
Labels: meta.alpha-n

#332 feat(env): update Hekla && mainnet bootnodes
  .env.sample
  .env.sample.hekla
Labels: meta.alpha-7, meta.mainnet

#336 feat(prover,proposer): bump client version
  docker-compose.yml
  script/start-prover-relayer.sh
Labels: area.client, area.prover, area.proposer, meta.mainnet

#337 chore(docker): bump Hekla client tag
  docker-compose-hekla.yml
Labels: meta.alpha-7, area.proposer
