Repository taikoxyz/simple-taiko-node, pull requests merged in 2024-05, with the labels that each got.

#235 feat: Updated .env.sample to clarify token amounts
  .env.sample
Labels: area.client

#225 feat: docker-compose.yml formatting
  docker-compose.yml
Labels: type.enhancement

#237 docs: Update .env.sample
  .env.sample
Labels: area.docs

#238 feat: add condition to check requirement variables for proposer/prover
  script/start-proposer.sh
  script/start-prover-relayer.sh
Labels: area.client

#249 chore(ci): introduce `Close Inactive Issues` workflow
  .github/workflows/close-inactive-issues.yml
Labels: area.client

#286 chore: bump `taiko-client` tag
  docker-compose.yml
Labels: area.client
