Repository taikoxyz/simple-taiko-node, pull requests merged in 2025-07, with the labels that each got.

#397 chore(docker): bump client hotfix version
  docker-compose.yml
Labels: area.client, meta.mainnet

#401 chore(driver): update hekla p2p bootnodes
  .env.sample.hekla
  docker-compose-hekla.yml
  script/start-driver-hekla.sh
Labels: area.client

#403 feat(driver,prover): update mainnet bootnodes and scripts
  .env.sample
  docker-compose.yml
  script/start-driver.sh
  script/start-proposer.sh
  script/start-prover-relayer.sh
Labels: area.client, area.prover

#405 chore(driver): add flag to enable p2p network
  .env.sample
  .env.sample.hekla
  .gitignore
  docker-compose-hekla.yml
  docker-compose.yml
  script/start-driver-hekla.sh
  script/start-driver.sh
Labels: area.client
