Repository taikoxyz/simple-taiko-node, pull requests merged in 2025-02, with the labels that each got.

#362 fix(driver): fix image tag
  docker-compose.yml
Labels: area.client

#366 fix(prover): remove deprecated flag
  script/start-prover-relayer.sh
Labels: area.prover

#367 chore(docker): update Hekla `taiko-client` tags
  docker-compose-hekla.yml
Labels: area.client, meta.alpha-7
