Repository taikoxyz/simple-taiko-node, pull requests merged in 2025-01, with the labels that each got.

#349 chore(env): update `.env.sample.hekla`
  .env.sample.hekla
Labels: meta.alpha-7

#351 chore(prover,proposer,driver): upgrade client version to `0.43.0` on Hekla
  .env.sample
  .env.sample.hekla
  docker-compose-hekla.yml
  script/start-proposer-hekla.sh
  script/start-prover-relayer-hekla.sh
  script/start-prover-relayer.sh
Labels: area.client, meta.alpha-7

#353 feat(driver,prover,proposer): bump client version
  docker-compose-hekla.yml
Labels: area.client, meta.alpha-7

#355 chore(prover,proposer): script and env improvements
  .env.sample
  .env.sample.hekla
  script/start-proposer-hekla.sh
  script/start-proposer.sh
  script/start-prover-relayer-hekla.sh
  script/start-prover-relayer.sh
Labels: meta.alpha-7, meta.mainnet

#359 chore(repo): upgrade geth version
  docker-compose-hekla.yml
  docker-compose.yml
Labels: area.client, meta.alpha-7, meta.mainnet
